FROM ruby:2.6.3

ENV RAILS_ENV production

RUN apt-get update -qq && apt-get install -y mysql-client

WORKDIR /app/backend

COPY backend/Gemfile backend/Gemfile.lock /app/backend/

RUN bundle install --jobs=4 --path=/bundle --deployment

COPY backend /app/backend/

ARG IIDXIO_VERSION
ENV IIDXIO_VERSION $IIDXIO_VERSION

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
