coverage:
  status:
    patch: off # TODO
    project:
      default:
        target: 50% # TODO
      backend:
        target: 0% # TODO
        paths: 'backend/'
      frontend:
        target: 0% # TODO
        paths: 'frontend/'
