require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'db/schemas/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*.rake'

Style/Documentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent
