version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -u root -ppassword']
      interval: 5s
      timeout: 10s
      retries: 3
  redis:
    image: redis:4.0.11-stretch
    ports:
      - '6379:6379'
  rails: &app_base
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    working_dir: /app/backend
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - spring:/tmp/spring
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      IIDX_IO_TEXTAGE_CACHE_PATH: /app/.cache
      SPRING_SOCKET: /tmp/spring/spring.sock
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    ports:
      - '5000:3000'
  spring: &spring
    <<: *app_base
    command: bin/spring server
    ports: []
    tty: false
    stdin_open: false
    restart: on-failure:3
  backend_watcher:
    <<: *spring
    command: bundle exec guard -i
  next: &next
    build:
      context: .
      dockerfile: ./docker/next/Dockerfile
    working_dir: /app/frontend
    command: yarn run dev
    volumes:
      - .:/app
      - node_modules:/app/frontend/node_modules
    environment:
      API_URL: http://localhost:5000/graphql
    ports:
      - '3000:3000'
  gql_gen:
    <<: *next
    command: yarn run gql:gen --watch
    tty: false
    stdin_open: false
    ports: []
volumes:
  db_data:
  bundle:
  node_modules:
  spring:
