FROM node:12.16.2-alpine

ENV NODE_ENV production

WORKDIR /app/frontend

COPY frontend/package.json frontend/yarn.lock /app/frontend/

RUN NODE_ENV=development yarn install --frozen-lockfile

COPY frontend /app/frontend/

ARG IIDXIO_VERSION
ENV IIDXIO_VERSION $IIDXIO_VERSION

RUN yarn run build:prod

CMD ["yarn", "run", "start:prod"]
