require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2

Rails:
  Enabled: true

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/MultilineBlockChain:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/ClassStructure:
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    IIDXIO: iidx_io
    IIDXIOSchema: iidx_io_schema

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false
