require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1

Rails:
  Enabled: true

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/MultilineBlockChain:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/ClassStructure:
  Enabled: true
  Categories:
    association:
      - belongs_to
      - has_many
      - has_one
    validation:
      - validates
      - validate
    attribute:
      - attr_accessor
      - attr_reader
      - attr_writer
    delegation:
      - delegate
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - attribute
    - validation
    - delegation
    - public_class_methods
    - initializer
    - public_methods
    - protected_methods
    - private_methods

RSpec/FilePath:
  CustomTransform:
    IIDXIO: iidx_io
    IIDXIOSchema: iidx_io_schema

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
