# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '~> 5.2.3'

gem 'activerecord-import'
gem 'bcrypt', '~> 3.1.13'
gem 'enumerize'
gem 'faraday'
gem 'faraday-http-cache'
gem 'firebase_id_token'
gem 'graphql'
gem 'graphql-batch'
gem 'jwt'
gem 'mini_racer'
gem 'mysql2', '>= 0.3.18', '< 0.6'
gem 'puma', '~> 4.1'
gem 'rack-cors'
gem 'rails-i18n'
gem 'redis'
gem 'ridgepole'
gem 'virtus'

group :development, :test do
  gem 'bullet'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'tapp'
  gem 'webmock'
end

group :development do
  gem 'guard', require: false
  gem 'guard-rake', require: false
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'codecov', require: false
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec_junit_formatter'
  gem 'simplecov'
end
