version: 2
jobs:
  build_backend:
    docker:
      - image: circleci/ruby:2.5.0
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.23
    working_directory: ~/repo/backend
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-backend-bundler-{{ checksum "Gemfile.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-backend-bundler-'
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: '{{ .Environment.CACHE_VERSION }}-backend-bundler-{{ checksum "Gemfile.lock" }}'
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: bundle exec rake db:setup
      - run:
          name: run linters
          command: bundle exec rubocop
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  build_frontend:
    docker:
      - image: circleci/node:10.12.0
    working_directory: ~/repo/frontend
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-frontend-yarn-{{ checksum "yarn.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-frontend-yarn-'
      - run:
          name: install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: '{{ .Environment.CACHE_VERSION }}-frontend-yarn-{{ checksum "yarn.lock" }}'
      - run:
          name: setup .env
          command: cp ~/repo/.env{.sample,}
      - run:
          name: check diff of generated files
          command: |
            dir="$(mktemp -d)"
            yarn run gql:gen --out "$dir/index.ts"
            diff -uN queries/index.ts "$dir/index.ts"
      - run:
          name: run linters
          command: yarn run lint:ts
      - run:
          name: run tests
          command: |
            yarn run test
            yarn run codecov --root=~/repo

  prettier:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-yarn-{{ checksum "yarn.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-yarn-'
      - run:
          name: install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: '{{ .Environment.CACHE_VERSION }}-yarn-{{ checksum "yarn.lock" }}'
      - run: yarn run format

workflows:
  version: 2
  build:
    jobs:
      - build_frontend
      - build_backend
      - prettier
