# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/redis-namespace/all/redis-namespace.rbi
#
# redis-namespace-1.6.0
class Redis
end
class Redis::Namespace
  def _client; end
  def add_namespace(key); end
  def call_site; end
  def call_with_namespace(command, *args, &block); end
  def client; end
  def clone_args(arg); end
  def create_enumerator(&block); end
  def deprecations?; end
  def eval(*args); end
  def exec; end
  def initialize(namespace, options = nil); end
  def inspect; end
  def keys(query = nil); end
  def method_missing(command, *args, &block); end
  def multi(&block); end
  def namespace(desired_namespace = nil); end
  def namespace=(arg0); end
  def namespaced_block(command, &block); end
  def pipelined(&block); end
  def redis; end
  def rem_namespace(key); end
  def respond_to?(command, include_private = nil); end
  def respond_to_missing?(command, include_all = nil); end
  def self_respond_to?(*arg0); end
  def type(key); end
  def warning; end
  def warning=(arg0); end
  def warning?; end
end
