# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tapp/all/tapp.rbi
#
# tapp-1.5.1
module Tapp
  def self.config; end
  def self.configure(&block); end
  extend Tapp::Deprecated
end
class Tapp::Configuration
  def default_printer; end
  def default_printer=(arg0); end
  def initialize; end
  def report_caller; end
  def report_caller=(arg0); end
  def reset; end
end
module Tapp::Deprecated
  def verbose; end
  def verbose=(bool); end
end
module Tapp::Printer
  def self.instance(name); end
  def self.register(name, printer); end
end
class Tapp::Printer::Base
  def print(*args); end
  def self.allocate; end
  def self.instance; end
  def self.new(*arg0); end
  extend Singleton::SingletonClassMethods
  include Singleton
end
module Tapp::Util
  def report_called; end
  def self.report_called; end
end
module Tapp::ObjectExtension
  def tapp(printer = nil); end
  def taputs(&block); end
end
class Tapp::Printer::PrettyPrint < Tapp::Printer::Base
  def print(*args); end
  def self.instance; end
end
class Tapp::Printer::Puts < Tapp::Printer::Base
  def print(*args); end
  def self.instance; end
end
class Object < BasicObject
  include Tapp::ObjectExtension
end
